
server:
  port: 8080

#http://192.168.18.232/root/{application}.git
spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.168.18.232/root/springcloud_config_server_test.git
          search-paths:
            - foo
            - bar